<<<<<<< HEAD
x=msgbox("salam")
x=msgbox("shemordan baladi?")
x=msgbox("bia baham beshmorim")
x=msgbox("hazeri?")
do
x=msgbox("1")
x=msgbox("2")
x=msgbox("3")
x=msgbox("4")
x=msgbox("5")
x=msgbox("6")
x=msgbox("7")
x=msgbox("8")
x=msgbox("khaste ke nashodi?")
x=msgbox("khube")
x=msgbox("9")
x=msgbox("10")
x=msgbox("11")
x=msgbox("12")
x=msgbox("13")
x=msgbox("14")
x=msgbox("15")
x=msgbox("16")
x=msgbox("17")
x=msgbox("20")
x=msgbox("20 akhe?")
x=msgbox("bade 17 mishe 18 bisavad")
x=msgbox("berim az aval")
=======
x=msgbox("salam")
x=msgbox("shemordan baladi?")
x=msgbox("bia baham beshmorim")
x=msgbox("hazeri?")
do
x=msgbox("1")
x=msgbox("2")
x=msgbox("3")
x=msgbox("4")
x=msgbox("5")
x=msgbox("6")
x=msgbox("7")
x=msgbox("8")
x=msgbox("khaste ke nashodi?")
x=msgbox("khube")
x=msgbox("9")
x=msgbox("10")
x=msgbox("11")
x=msgbox("12")
x=msgbox("13")
x=msgbox("14")
x=msgbox("15")
x=msgbox("16")
x=msgbox("17")
x=msgbox("20")
x=msgbox("20 akhe?")
x=msgbox("bade 17 mishe 18 bisavad")
x=msgbox("berim az aval")
>>>>>>> fffd64cd92285e20200459bb7f0dd4ceced4eab6
loop